# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  toolName: 'Seatbelt'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -Uri "https://github.com/mkaring/ConfuserEx/releases/download/v1.4.1/ConfuserEx-CLI.zip" -Out confuserex.zip
      Expand-Archive confuserex.zip
      '<project outputDir="." baseDir="." xmlns="http://confuser.codeplex.com">
        <rule pattern="true" inherit="false">
          <protection id="anti debug" />
          <protection id="anti dump" />
          <protection id="anti ildasm" />
          <protection id="anti tamper" />
          <protection id="constants" />
          <protection id="ctrl flow" />
          <protection id="invalid metadata" />
          <protection id="resources" />
          <protection id="rename" />
        </rule>
        <module path="Seatbelt\bin\Release\Seatbelt.exe" />
      </project>' | ac Confuser.crproj
      .\confuserex\Confuser.CLI.exe Confuser.crproj
    failOnStderr: true

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'offensive-tooling-artifact-storage'
    #contents: '**/*.exe'
    contents: '$(toolName)\bin\Release\$(toolName).exe'
    targetFolder: '/var/www/html'
    readyTimeout: '20000'
    failOnEmptySource: true
    flattenFolders: true